### ISSUE TITLE
Issue - All nodes get the same IP Address, even the NGINX LoadBalancer

### ISSUE THREAD

**Issue by bhott1287** [David-VTUK/Rancher-K3s-vSphere#1]
### Variables (variables.tfvars) below, but terraform completes the creation of the nodes, and the load balancer.  Upon completion everything has the same IP address.  

Maybe there is a little confusion regarding the documentation on the variables.tfvars or a possible bug.  The templating of the modules/nodes/templates/metadata.yml.tpl seems to not be running through the count of the **resource "vsphere_virtual_machine" "k3s-nodes**" - every node gets the same IP address.

vsphere_server     = "10.XX.XX.XXX"
vsphere_user       = "user@vsphere.local"
vsphere_password   = "password"
vsphere_datacenter = "Datacenter"
vsphere_cluster    = "Cluster"
vsphere_network    = "dev"

vm_prefix     = "k3s-ranch-node-"
vm_count      = "3"
vm_datastore  = "vsanDatastore"
vm_cpucount   = "8"
vm_memory     = "8192"
vm_domainname = "work.lab"
vm_network    = "10.XX.XX."
vm_netmask    = "24"
vm_gateway    = "10.XX.XX.1"
vm_dns        = "10.XX.XX.XX"

lb_address    = "10.XX.XX.33"
lb_prefix     = "k3s-ranch-lb"
lb_datastore  = "vsanDatastore"
lb_cpucount   = "1"
lb_memory     = "1024"
lb_domainname = "work.lab"
lb_netmask    = "24"
lb_gateway    = "10.XX.XX.1"
lb_dns        = "10.XX.XX.XX"

k3s_secret = "S87sd6f7od87D96Fd"

certmanager_version = "0.15.0"

rancher_hostname    = "k3rancher.work.lab"
rancher_version     = "2.4.5"

host_username = "user"
host_password      = "password"

@David-VTUK

**Comment by David-VTUK** [comment]
Hi @bhott1287.

I can't recreate the issue you're experiencing - I've just tested with a new subnet range which also works. VM's with the same IP (from my experience) has come from DHCP requests where machine-id hasn't been zeroed out. If it's not your intention to use DHCP, then can you please try the following:

* Check your state file for `default_ip_address` values - these should be unique.
* The cloud-init OVF integration prerequisites are met on the Template VM (`curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh -`)
* Cloud-init is in a state whereby it's accepting of new data (Convert the Template to VM, power on, run `cloud-init clean --logs`. shutdown, convert back into a template.

**Comment by bhott1287** [comment]
@David-VTUK 

There is no DHCP in the environment, so there shouldn't be any DHCP requests.  

To verify the list of items you suggested:
- The default_ip_address values in the state file are all the same IP address. 
- I assumed the packer template referenced here [https://github.com/David-VTUK/Rancher-Packer/tree/master/vSphere/ubuntu_2004_cloud_init_guestinfo](url) was setup.  
- I will reverify the cloud-init state and try again.

**Comment by David-VTUK** [comment]
Interesting. You shouldn't need to do that then.

Are you using Terraform 0.13?

**Comment by David-VTUK** [comment]
Oh, change

vm_count = "3"

to 

vm_count = 3

That variable is a `number` type. Same with the CPU count and Memory.

Edit : My fault. I incorrectly populated the variables.tfvars.example file. My apologies.

**Comment by bhott1287** [comment]
@David-VTUK 

Changed the values from strings to number, but still seeing the same issues.   That was a good catch.  I hadn't noticed that until you said something. 

I am thinking there is an issue with the template.  The template seems to have an IP address that lingers from the time it was setup using Packer.  If the 01-netcfg.yaml is cleared, terraform creates the k3s nodes and they receive IPv6 addresses.  I think it's something unrelated to the code at this point.  I could be wrong, but I will dig further and keep you updated.

**Comment by David-VTUK** [comment]
@bhott1287 

I've modified both the ubuntu_1804_no_dhcp and created ubuntu_2004_no_dhcp templates in the Packer repo to add some extra items in the scripts to remove any lingering networking config from the Template creation phase - might be helpful.

**Comment by picoroma** [comment]
Hi!
I performing the same issue (all VM come up with same IP address.) I'm using DHCP to assign the IP address, and I think due to fact that these VM come from the same template (maybe the same machineID)  makes the DHCP assign the same IP.
Is possible ?
P,

**Comment by picoroma** [comment]
I solved the problem od "same IP address" editing the VM template.
In details with this command:
truncate -s 0 /etc/machine-id
And recreating the template ex-novo.
UNfortunately - after that I have another problem with script /tmp/terraform_1522080666.sh - that do not install ngnix on LB server.

**Comment by David-VTUK** [comment]
Good spot with machine-id. I remember I had to do this with my Packer templates.

@picoroma - Do you have any more logs as to why nginx doesn't get installed?

**Comment by David-VTUK** [comment]
Discussed outside of ticket - cloud-init issue.
