### ISSUE TITLE
After VM creation - nginx installation script do not start\work

### ISSUE THREAD

**Issue by picoroma** [David-VTUK/Rancher-K3s-vSphere#4]
Hi! After I solved the problem of same IP address (with DHCP) the script seems to do on.
The next step is to log in SSH to load balancer..
And this works fine. But the script /tmp/terraform_473384145.sh that contains the command to install NGINX - do now work:
#!/bin/sh
sudo apt update && sudo apt install nginx -y
sudo mv /root/nginx.conf /etc/nginx/nginx.conf
sudo service nginx restart

Also the /root/nginx.conf file is missing on VM.
A ps -ef on VM gives me the result in attach.
![Screenshot_144](https://user-images.githubusercontent.com/23618664/107144190-ce4ae800-6939-11eb-95b8-20f8e3775a53.jpg)

λ terraform version
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/vsphere v1.24.3

**Comment by David-VTUK** [comment]
Can you grab the logs from the terraform output when it's trying to install nginx, please?

Also, what VM template are you basing this on?

**Comment by picoroma** [comment]
The VM template is a Ubuntu 20.04, I have installed with standar installation. No SW added except for "Cloud-Init Datasource for VMware GuestInfo" as per prerequisites.
The terraform log is not to big help..
After the SSH login to VM and the "ask for sudo pswd" - No much more is displayed.

**Comment by DH-Rancher** [comment]
You likely need to configure passwordless sudo for the user you're ssh'ing as.

**Comment by picoroma** [comment]
OK.
After I make the sudo with nopswd for my user. The installations goes on....
Untill I arrive to this error :

null_resource.wait_for_rancher (local-exec): Executing: ["cmd" "/C" "      while true; do curl -kv https://\"tf-rancher.bgp.locale\" 2>&1 | grep -q \"dynamiclistener-ca\"; if [ $? != 0 ]; then echo \"Rancher URL isn't ready yet\"; sleep 5; continue; fi; break; done; echo \"Rancher URL is Ready\";\n"]

Is this possible because I do not yet create the DNS entry ?
But How can I create an entry into DNS before I know the IP oh the LB ?
I need to assume the IP of LB as per var "lb_address" ?
BUT the LB created by script, has a different IP than "lb_address".....

**Comment by David-VTUK** [comment]
As per https://github.com/David-VTUK/Rancher-K3s-vSphere#prerequisites the idea is to create a DNS record for your rancher URL pointing at `lb_address`. `lb_address` should get applied to the vm acting as your nginx lb. If it's not, then I would assume the vm template doesn't have the guest info add-on installed or DHCP may be overriding it.

**Comment by picoroma** [comment]
There is some problem.
The VM template has all the same hostname, of course. Maybe this do not helps!
The DHCP ( I do not know why) do not assign to LB VM, the IP i inserted into lb_address variable.

**Comment by picoroma** [comment]
I started with a new fresh folder of script files.
Firt of all - I have some WARNING related to variable user in an old way - deprecated in latest release of Terraform.
I have to correct some line in main.tf file.
After that I start the deploy but, after the creation of the VM
I have problem with the installation of K3s.
See attached file (TF log)
[tf-rancher-log2.txt](https://github.com/David-VTUK/Rancher-K3s-vSphere/files/5942182/tf-rancher-log2.txt)

If you are into Rancher SLACK Channel "general" you can find me as "PiCo" user. THX

**Comment by DH-Rancher** [comment]
```
module.k3s.null_resource.k3s_subsequent_nodes[0] (remote-exec): Job for k3s.service failed because the control process exited with error code.
module.k3s.null_resource.k3s_subsequent_nodes[0] (remote-exec): See "systemctl status k3s.service" and "journalctl -xe" for details.
```

Looks like k3s couldn't spin up - need to identify why.

**Comment by David-VTUK** [comment]
```
module.k3s.null_resource.k3s_subsequent_nodes[0] (remote-exec): Job for k3s.service failed because the control process exited with error code.
module.k3s.null_resource.k3s_subsequent_nodes[0] (remote-exec): See "systemctl status k3s.service" and "journalctl -xe" for details.
```

Looks like k3s couldn't spin up - need to identify why.

**Comment by David-VTUK** [comment]
Discussed outside of ticket.
